In [1]:
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import time
import re

In [2]:
# let's first connect to web driver
driver=webdriver.Chrome(r'C:\Users\DELL\Downloads\chromedriver_win32\chromedriver.exe')

### Q1.Scrape the details of most viewed videos on YouTube from Wikipedia.
### Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
### You need to find following details:
### A) Rank
### B) Name
### C) Artist
### D) Upload date
### E) Views

In [3]:
url="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

In [25]:
Rank=[]
Name=[]
Artist=[]
Views=[]
Upload_date=[]
try:
    ranktags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[1]')
    for i in ranktags[:30]:
        Rank.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    ranktags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[1]')
    for i in ranktags[:30]:
        Rank.append(i.text)

try:
    nametags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[2]')
    for i in nametags[:30]:
        Name.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    ranktags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[2]')
    for i in nametags[:30]:
        Name.append(i.text)

try:
    artisttags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[3]')
    for i in artisttags[:30]:
        Artist.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    artisttags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[2]')
    for i in artisttags[:30]:
        Artist.append(i.text)

try:
    viewstags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[4]')
    for i in viewstags[:30]:
        Views.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    viewstags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[4]')
    for i in viewstags[:30]:
        Views.append(i.text)

try:
    datetags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[5]')
    for i in datetags[:30]:
        Upload_date.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    datetags=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody[1]/tr/td[5]')
    for i in datetags[:30]:
        Upload_date.append(i.text)
        
video=pd.DataFrame({'Rank':Rank,'Name':Name,'Artist':Artist,'Views':Views,'Upload Date':Upload_date})
video

,Rank,Name,Artist,Views,Upload Date
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,10.23,"June 17, 2016"
1,2.,"""Despacito""[6]",Luis Fonsi,7.75,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.18,"October 8, 2016"
3,4.,"""Shape of You""[13]",Ed Sheeran,5.62,"January 30, 2017"
4,5.,"""See You Again""[15]",Wiz Khalifa,5.42,"April 6, 2015"
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,5.01,"May 2, 2018"
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,4.56,"February 27, 2018"
7,8.,"""Masha and the Bear – Recipe for Disaster""[22]",Get Movies,4.48,"January 31, 2012"
8,9.,"""Phonics Song with Two Words""[23]",ChuChu TV,4.48,"March 6, 2014"
9,10.,"""Uptown Funk""[24]",Mark Ronson,4.47,"November 19, 2014"
10,11.,"""Gangnam Style""[25]",Psy,4.35,"July 15, 2012"
11,12.,"""Dame Tu Cosita""[30]",El Chombo,3.86,"April 5, 2018"
12,13.,"""Wheels on the Bus""[31]",Cocomelon – Nursery Rhymes,3.70,"May 24, 2018"
13,14.,"""Sugar""[32]",Maroon 5,3.65,"January 14, 2015"
14,15.,"""Roar""[33]",Katy Perry,3.53,"September 5, 2013"
15,16.,"""Sorry""[34]",Justin Bieber,3.51,"October 22, 2015"
16,17.,"""Counting Stars""[35]",OneRepublic,3.51,"May 31, 2013"
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,3.41,"October 7, 2014"
18,19.,"""Girls Like You""[37]",Maroon 5,3.24,"May 31, 2018"
19,20.,"""Axel F""[38]",Crazy Frog,3.24,"June 16, 2009"
20,21.,"""Faded""[39]",Alan Walker,3.23,"December 3, 2015"
21,22.,"""Dark Horse""[40]",Katy Perry,3.23,"February 20, 2014"
22,23.,"""Let Her Go""[41]",Passenger,3.18,"July 25, 2012"
23,24.,"""Bailando""[42]",Enrique Iglesias,3.17,"April 11, 2014"
24,25.,"""Lean On""[43]",Major Lazer,3.17,"March 22, 2015"
25,26.,"""Shake It Off""[44]",Taylor Swift,3.15,"August 18, 2014"
26,27.,"""Baa Baa Black Sheep""[45]",Cocomelon – Nursery Rhymes,3.14,"June 25, 2018"
27,28.,"""Perfect""[46]",Ed Sheeran,3.10,"November 9, 2017"
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,3.06,"June 4, 2010"
29,30.,"""Mi Gente""[48]",J Balvin,3.04,"June 29, 2017"

### Q2. Scrape the details team India’s international fixtures from bcci.tv.
### Url = https://www.bcci.tv/.
### You need to find following details:
### A) Match title (I.e. 1st ODI)
### B) Series
### C) Place
### D) Date
### E) Time
### Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [26]:
url='https://www.bcci.tv/'
driver.get(url)

In [27]:
try:
    international_btn=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')
    international_btn.click()
except NoSuchElementException as e:
    print("Exception Raised ",e)
    driver.get(url)
    international_btn=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')
    international_btn.click()

In [47]:
Match_title=[]
Series=[]
Place=[]
Date=[]
Time=[]
try:
    titletags=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in titletags:
        Match_title.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    titletags=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in titletags:
        Match_title.append(i.text)

try:
    seriestags=driver.find_elements_by_xpath('//span[@class="ng-binding"]')
    for i in seriestags:
        Series.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    seriestags=driver.find_elements_by_xpath('//span[@class="ng-binding"]')
    for i in seriestags:
        Series.append(i.text)

try:
    placetags=driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]')
    for i in placetags:
        Place.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    placetags=driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]')
    for i in placetags:
        Place.append(i.text)

try:
    datetags=driver.find_elements_by_xpath('//h5[@class="ng-binding"]')
    for i in datetags:
        Date.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    datetags=driver.find_elements_by_xpath('//h5[@class="ng-binding"]')
    for i in datetags:
        Date.append(i.text)

try:
    timetags=driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]')
    for i in timetags:
        Time.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    timetags=driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]')
    for i in timetags:
        Time.append(i.text)
        
fixtures=pd.DataFrame({'Match Title':Match_title,'Series':Series,'Place':Place,'Date':Date,'Time':Time})
fixtures

,Match Title,Series,Place,Date,Time
0,5th ODI -,INDIA WOMEN TOUR OF NEW ZEALAND ODI SERIES 2022,"John Davies Oval,",24 FEB 2022,3:30 AM IST
1,1st T20I -,SRI LANKA TOUR OF INDIA T20 SERIES 2022,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,24 FEB 2022,7:00 PM IST
2,2nd T20I -,SRI LANKA TOUR OF INDIA T20 SERIES 2022,"Himachal Pradesh Cricket Association Stadium,",26 FEB 2022,7:00 PM IST
3,3rd T20I -,SRI LANKA TOUR OF INDIA T20 SERIES 2022,"Himachal Pradesh Cricket Association Stadium,",27 FEB 2022,7:00 PM IST
4,1st Test -,SRI LANKA TOUR OF INDIA TEST SERIES 2022,"Punjab Cricket Association IS Bindra Stadium,",4 MAR 2022,9:30 AM IST
5,1st ODI -,ICC WOMENS WORLD CUP 2022,"Bay Oval,",6 MAR 2022,6:30 AM IST
6,2nd ODI -,ICC WOMENS WORLD CUP 2022,"Seddon Park,",10 MAR 2022,6:30 AM IST
7,2nd Test -,SRI LANKA TOUR OF INDIA TEST SERIES 2022,"M Chinnaswamy Stadium,",12 MAR 2022,12:30 PM IST

### Q3. Scrape the details of selenium exception from guru99.com.
### Url = https://www.guru99.com/
### You need to find following details:
### A) Name
### B) Description
### Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [38]:
url='https://www.guru99.com/'
driver.get(url)

In [39]:
try:
    seleniumbtn=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
    seleniumbtn.click()
    time.sleep(2)
    exptnbtn=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a')
    exptnbtn.click()
except  NoSuchElementException as e:
    print("Exception Raised ",e)
    driver.get(url)
    seleniumbtn=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
    seleniumbtn.click()
    time.sleep(2)
    exptnbtn=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a')
    exptnbtn.click()

In [44]:
Name=[]
try:
    nametags=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
    for i in nametags:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
Description=[]
try:
    desctags=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
    for i in desctags:
        Description.append(i.text)
except NoSuchElementException:
    Description.append('-')

In [46]:
selenium=pd.DataFrame({'Exception Name':Name,'Description':Description})
selenium

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

### Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
### Url = http://statisticstimes.com/
### You have to find following details:
### A) Rank
### B) State
### C) GSDP
### D) GSDP
### E) Share
### F) GDP($ billion)
### Note: - From statisticstimes home page you have to reach to economy page through code.

In [11]:
url = 'https://www.statisticstimes.com/'
driver.get(url)

In [12]:
try:
    economybtn=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
    economybtn.click()
    indiabtn=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
    indiabtn.click()
    gdpbtn=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
    gdpbtn.click()
except NoSuchElementException as e:
    print("Exception Raised ",e)
    driver.get(url)
    economybtn=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
    economybtn.click()
    indiabtn=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
    indiabtn.click()
    gdpbtn=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
    gdpbtn.click()

In [30]:
Rank=[]
State=[]
GSDP_1920=[]
GSDP_1819=[]
Share=[]
GDP_billion=[]
try:
    ranktags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[1]')
    for i in ranktags:
        Rank.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    ranktags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[1]')
    for i in ranktags:
        Rank.append(i.text)

try:
    statetags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[2]')
    for i in statetags:
        State.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    statetags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[2]')
    for i in statetags:
        State.append(i.text)

try:
    gsdptags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gsdptags:
        GSDP_1920.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    gsdptags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gsdptags:
        GSDP_1920.append(i.text)

try:
    gsdptags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gsdptags:
        GSDP_1819.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    gsdptags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gsdptags:
        GSDP_1819.append(i.text)

try:
    sharetags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[5]')
    for i in sharetags:
        Share.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    sharetags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[5]')
    for i in sharetags:
        Share.append(i.text)

try:
    gdptags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdptags:
        GDP_billion.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    gdptags=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdptags:
        GDP_billion.append(i.text)
        
GDP=pd.DataFrame({'Rank':Rank,'State':State,'GSDP 19-20':GSDP_1920,'GSDP 18-19':GSDP_1819,'Share':Share,'GDP($ billion)':GDP_billion})
GDP

,Rank,State,GSDP 19-20,GSDP 18-19,Share,GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

### Q5. Scrape the details of trending repositories on Github.com.
### Url = https://github.com/
### You have to find the following details:
### A) Repository title
### B) Repository description
### C) Contributors count
### D) Language used

In [31]:
url='https://github.com/'
driver.get(url)

In [32]:
try:
    explorebtn=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
    explorebtn.click()
    trendingbtn=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
    trendingbtn.click()
except  NoSuchElementException as e:
    print("Exception Raised ",e)
    driver.get(url)
    explorebtn=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
    explorebtn.click()
    trendingbtn=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
    trendingbtn.click()

In [52]:
Urls=[]
urltags=driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]/a')
for i in urltags:
    Urls.append(i.get_attribute("href"))

In [60]:

Title=[]
try:
    titletags=driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]')
    for i in titletags:
        Title.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    titletags=driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]')
    for i in titletags:
        Title.append(i.text)
Description=[]
try:
    decriptiontags=driver.find_elements_by_xpath('//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in decriptiontags:
        Description.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    decriptiontags=driver.find_elements_by_xpath('//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in descriptiontags:
        Description.append(i.text)
Contricount=[]
try:
    counttags=driver.find_elements_by_xpath('//div[@class="f6 color-fg-muted mt-2"]/a[2]')
    for i in counttags:
        Contricount.append(i.text)
except NoSuchElementException as e:
    print("Exception Raised ",e)
    counttags=driver.find_elements_by_xpath('//div[@class="f6 color-fg-muted mt-2"]/a[2]')
    for i in counttags:
        Contricount.append(i.text)
Language=[]
try:
    langtags=driver.find_elements_by_xpath('//span[@class="d-inline-block ml-0 mr-3"]/span[2]')
    for i in langtags:
        Language.append(i.text)
except NoSuchElementException:
    Language.append('-')

In [83]:
repo=pd.DataFrame({'Title':Title,'Description':Description,'Contributors':Contricount,'Language':Language})
repo

,Title,Description,Contributors,Language
0,louisyoungx / JD-SHOPPER,"京东自动下单 (自动登录,指定时间预约商品,商品补货监控,自动加购物车,自动下单)",201,Python
1,github / advisory-database,Security vulnerability database inclusive of C...,21,C
2,netdata / netdata,"Real-time performance monitoring, done right! ...","5,197",C++
3,jrouwe / JoltPhysics,A multi core friendly rigid body physics and c...,47,C++
4,KumarRobotics / kr_autonomous_flight,Autonomous flight system for aerial robots,28,Markdown
5,nusr / hacker-laws-zh,"💻📖对开发人员有用的定律、理论、原则和模式。(Laws, Theories, Princip...",907,TypeScript
6,anderspitman / awesome-tunneling,List of ngrok alternatives and other ngrok-lik...,140,Python
7,labuladong / fucking-algorithm,刷算法全靠套路，认准 labuladong 就够了！English version supp...,"20,274",TypeScript
8,withfig / autocomplete,Fig adds autocomplete to your terminal.,"2,877",Python
9,commaai / openpilot,openpilot is an open source driver assistance ...,"6,089",Vue
10,planetscale / beam,A simple message board for your organization o...,19,C#
11,KurtBestor / Hitomi-Downloader,🍰 Desktop utility to download images/videos/mu...,792,Python
12,VoronDesign / Voron-2,Voron 2 CoreXY 3D Printer design,582,TypeScript
13,vueComponent / ant-design-vue,🌈 An enterprise-class UI components based on A...,"2,945",C++
14,SebLague / Geographical-Adventures,"FastAPI framework, high performance, easy to l...",15,Go
15,tiangolo / fastapi,快速高效搭建可视化拖拽平台,"3,209",Haskell
16,H5-Dooring / dooringx,An open-source C++ library developed and used ...,239,TypeScript
17,facebook / folly,Yao A low code engine to create web services a...,"4,537",Java
18,YaoApp / yao,"Blazing fast, instant realtime GraphQL APIs on...",40,-
19,hasura / graphql-engine,Game Preservation Project,"2,193",-
20,skywind3000 / preserve-cd,😮 Core Interview Questions & Answers For Exper...,128,-
21,nkallen / plasticity,Anime Girls Holding Programming Books,14,-
22,doocs / advanced-java,《代码随想录》LeetCode 刷题攻略：200道经典题目刷题顺序，共60w字的详细图解，视...,"16,639",-
23,cat-milk / Anime-Girls-Holding-Programming-Books,-,445,-
24,youngyangyang04 / leetcode-master,-,"5,941",-

### 6. Scrape the details of top 100 songs on billiboard.com.
### Url = https:/www.billboard.com/
### You have to find the following details:
### A) Song name
### B) Artist name
### C) Last week rank
### D) Peak rank
### E) Weeks on board
### Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [3]:
url='https://www.billboard.com/'
driver.get(url)

In [4]:
try:
    chartbtn=driver.find_element_by_xpath('/html/body/div[4]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a')
    chartbtn.click()
    hotbtn=driver.find_element_by_xpath('/html/body/div[4]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a')
    hotbtn.click()
except NoSuchElementException as e:
    print("Exception Raised ",e)
    driver.get(url)
    chartbtn=driver.find_element_by_xpath('/html/body/div[4]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a')
    chartbtn.click()
    hotbtn=driver.find_element_by_xpath('/html/body/div[4]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a')
    hotbtn.click()

In [26]:
Rank=[]
try:
    ranktags=driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet"]')
    for i in ranktags:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')
Song_name=[]
try:
    nametags=driver.find_elements_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet"]')
    for i in nametags:
        Song_name.append(i.text)
except NoSuchElementException:
    Song_name.append('-')
try:
    nametag=driver.find_elements_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]')
    for i in nametag:
        Song_name.append(i.text)
except NoSuchElementException:
    Song_name.append('-') 
Artist_name=[]
try:
    arnametags=driver.find_elements_by_xpath('//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet"]')
    for i in arnametags:
        Artist_name.append(i.text)
except NoSuchElementException:
    Artist_name.append('-')
try:
    arnametag=driver.find_elements_by_xpath('//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
    for i in arnametag:
        Artist_name.append(i.text)
except NoSuchElementException:
    Artist_name.append('-')    
Weekrank=[]

try:
    lastranks=driver.find_elements_by_xpath('//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]/span[1]')
    for i in lastranks:
        Weekrank.append(i.text)
except NoSuchElementException:
    Weekrank.append('-')
Lastweek_rank=[]
for i in Weekrank[:200:2]:
    Lastweek_rank.append(i)
weeksonboard=[]
for i in Weekrank[1::2]:
    weeksonboard.append(i)
column=[]
try:
    columntags=driver.find_elements_by_xpath('//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"]')
    for i in columntags:
        column.append(i.text)
except NoSuchElementException:
    column.append('-') 
Peak_rank=[]
for i in column[1::2]:
    Peak_rank.append(i)

In [30]:
topsongs=pd.DataFrame({'Rank':Rank,'Song name':Song_name,'Artist name':Artist_name,'Last week rank':Lastweek_rank,'Weeks on board':weeksonboard,'Peak rank':Peak_rank})
topsongs

,Rank,Song name,Artist name,Last week rank,Weeks on board,Peak rank
0,1,We Don't Talk About Bruno,"Carolina Gaitan, Mauro Castillo, Adassa, Rhenz...",1,8,1
1,2,Heat Waves,Glass Animals,4,57,2
2,3,Easy On Me,Adele,3,19,1
3,4,abcdefu,GAYLE,7,13,4
4,5,Stay,The Kid LAROI & Justin Bieber,5,32,1
...,...,...,...,...,...,...
95,96,All Too Well (Taylor's Version),Taylor Swift,84,14,1
96,97,Come Back As A Country Boy,Blake Shelton,89,5,85
97,98,Iffy,Chris Brown,96,5,71
98,99,Home Sweet,Russell Dickerson,94,5,88
99,100,Too Easy,Gunna & Future,92,16,16

### Q7. Scrape the details of Data science recruiters from naukri.com.
### Url = https://www.naukri.com/
### You have to find the following details:
### A) Name
### B) Designation
### C) Company
### D) Skills they hire for
### E) Location
### Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
### click on search. All this should be done through code

In [47]:
url='https://www.naukri.com/hr-recruiters-consultants'
driver.get(url)

In [48]:
search_field=driver.find_element_by_xpath('//input[@class="sugInp"]')
search_field.send_keys('Data Science')

In [50]:
search_btn=driver.find_element_by_xpath('//button[@class="fl qsbSrch blueBtn"]')
search_btn.click()

In [61]:
recruiters_url=[]
urltags=driver.find_elements_by_xpath('//div[@class="outerRecSec"]/div/div[1]/div[1]/p/a[1]')
for i in urltags:
    recruiters_url.append(i.get_attribute('href'))

In [66]:
Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]
for url in recruiters_url:
    driver.get(url)
    try:
        nametags=driver.find_element_by_xpath('//h1[@class="fl ellipsis wLimit hd"]')
        Name.append(nametags.text)
    except NoSuchElementException:
        Name.append('-')
    time.sleep(1)
    try:
        desigtags=driver.find_element_by_xpath('//div[@class="ellipsis"]')
        Designation.append(desigtags.text)
    
    except NoSuchElementException:
        Designation.append('-')    
    time.sleep(1)    
    try:
        companytags=driver.find_element_by_xpath('//div[@class="rFrame fl infoWrapper"]/div[4]/a')
        Company.append(companytags.text)
    except NoSuchElementException:
        Company.append('-')
    time.sleep(1)    
    try:
        skilltags=driver.find_element_by_xpath('//div[@class="fl lPortn"]/p[1]')
        Skills.append(skilltags.text)
    except NoSuchElementException:
        Skills.append('-') 
    time.sleep(1)
    try:
        loctags=driver.find_element_by_xpath('//div[@class="rFrame fl infoWrapper"]/div[5]/a')
        Location.append(loctags.text)
    except NoSuchElementException:
        Location.append('-')

In [78]:
recruiters=pd.DataFrame({'Name':Name,'Designation':Designation,'Company':Company,'Skills':Skills,'Location':Location})
recruiters

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer , Internet Marketing Pro...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net , Java , Data Science , Linux Administrat...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Mid Level, Junior Level",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,", Mean Stack , javascript , angularjs , mongod...",Ahmedabad
4,subhas patel,Founder & CEO,LibraryXProject,"Hadoop , Spark , Digital Strategy , Data Archi...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and APAC,Recruitment - Lead Consultant,Apidel Technologies Division of Transpower,"Analytics , Business Intelligence , Business A...",Vadodara / Baroda
6,Institute for Financial Management and Research,Programme Manager,IFMR,Analytics & Business Intelligence,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning , algorithms , Go Getter , Co...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,-,Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Junior Level, Mid Level",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Mid Level, High Level",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa , Ui , ux , Java Developer , Java Architect...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,-,Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,-,Mumbai
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Junior Level, Mid Level",Hyderabad / Secunderabad
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,High Level,Chandigarh
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data , Hadoop , Data Analytics , Data Science",Bhopal
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,IT Skills,Pune
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"High Level, Mid Level",Pune
19,Manisha Yadav,HR Executive,Easi Tax,Mid Level,Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,IT-Software/Software Services,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE LIMITED,"Mid Level, Top Mangement Level",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics , Data Science , Machine Learni...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Junior Level, Mid Level",Pune
24,Shaun Rao,Manager - Human Resources,Exela Technologies,"Java , Net , Angularjs , Hr , Infrastructure ,...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Mid Level, High Level",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private Limited,"High Level, Top Mangement Level",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science , Hadoop , Rpas , Devops , Python...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing , Machine Learning , Neural ...",Others
29,Rajat Kumar,Founder & CEO,R.S Consultancy & Services,"Web Technologies , Project Management , Softwa...",Delhi
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"S. Finance Manager , Freshers , Experience , S...",Bengaluru / Bangalore
31,Avodha,Business Development Associate,Nikitha Palaparthi,-,Hyderabad / Secunderabad
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics , Managed Services , Team Leading",Mysoru / Mysore
33,Priya Khare,Senior Manager,Independent Consultant,-,Bengaluru / Bangalore
34,Amit Sharma,Consultant,ASCO consulting,-,New Delhi
35,Kanan,senior technology instructor,NY INST,"Mid Level, Junior Level",Chennai
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research & Consulting Co. India,-,Aligarh
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Junior Level, High Level",Salt Lake City
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Python , Php , Qa Automation , Ui , Wordpre",Pune
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,-,Bengaluru / Bangalore
40,Ankit Sinha,Head-Analytics,Suntech Global,-,Mumbai
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Top Mangement Level, Junior Level",Indore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science , Node.js , Angularjs",Bengaluru / Bangalore
43,Ashwini,"Director, Global Delivery",MRP Advisers,-,MYSORE
44,Balaji Kolli,Co-Founder,Saras Solutions India Pvt Ltd,-,Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"java , hadoop , r , Machine Learning , spark ,...",Bengaluru / Bangalore
46,ROHIT Kumar,Architect,LNT Private Limited,"Mid Level, High Level",Mumbai
47,Amir Chowdhury,Managing Partner,Granular.ai,-,
48,Radha Manivasagam,HR Executive,Techcovery,Junior Level,Bengaluru / Bangalore
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,-,Hyderabad / Secunderabad

### Q8. Scrape the details of Highest selling novels.
### Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
### You have to find the following details:
### A) Book name
### B) Author name
### C) Volumes sold
### D) Publisher
### E) Genre

#### This link is not reachable

### 9. Scrape the details most watched tv series of all time from imdb.com.
### Url = https://www.imdb.com/list/ls095964455/
### You have to find the following details:
### A) Name
### B) Year span
### C) Genre
### D) Run time
### E) Ratings
### F) Votes

In [3]:
url='https://www.imdb.com/list/ls095964455/'
driver.get(url)

In [4]:
Name=[]
Year_span=[]
Genre=[]
Run_time=[]
Ratings=[]
Votes=[]
try:
    nametags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/h3/a')
    for i in nametags:
        Name.append(i.text)
except NoSuchElementException:
    print("Exception Raised ",e)
    nametags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/h3/a')
    for i in nametags:
        Name.append(i.text)
        
try:
    yeartags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/h3/span[2]')
    for i in yeartags:
        Year_span.append(i.text)
except NoSuchElementException:
    print("Exception Raised ",e)
    yeartags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/h3/span[2]')
    for i in yeartags:
        Year_span.append(i.text)
        
try:
    genretags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p/span[5]')
    for i in genretags:
        Genre.append(i.text)
except NoSuchElementException:
    print("Exception Raised ",e)
    genretags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p/span[5]')
    for i in genretags:
        Genre.append(i.text)
        
try:
    timetags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p/span[3]')
    for i in timetags:
        Run_time.append(i.text)
except NoSuchElementException:
    print("Exception Raised ",e)
    timetags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p/span[3]')
    for i in timetags:
        Run_time.append(i.text)
        
try:
    ratingstag=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/div[1]/div/span[2]')
    for i in ratingstag:
        Ratings.append(i.text)
except NoSuchElementException:
    print("Exception Raised ",e)
    ratingstag=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/div[1]/div/span[2]')
    for i in ratingstag:
        Ratings.append(i.text)
        
try:
    votetags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p[4]/span[2]')
    for i in votetags:
        Votes.append(i.text)
except NoSuchElementException:
    print("Exception Raised ",e)
    votetags=driver.find_elements_by_xpath('//div[@class="lister-item mode-detail"]/div[2]/p[4]/span[2]')
    for i in votetags:
        Votes.append(i.text)

In [18]:
imbd=pd.DataFrame({'Name':Name,'Year span':Year_span,'Genre':Genre,'Run time':Run_time,'Ratings':Ratings,'Votes':Votes})
imbd

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,956,983"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"966,681"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"932,184"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"279,090"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"239,270"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,813"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"58,534"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"185,818"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"39,342"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"222,123"

### Q10. Details of Datasets from UCI machine learning repositories.
### Url = https://archive.ics.uci.edu/
### You have to find the following details:
### A) Dataset name
### B) Data type
### C) Task
### D) Attribute type
### E) No of instances
### F) No of attribute
### G) Year
### Note: - from the home page you have to go to the ShowAllDataset page through code.

In [3]:
url='https://archive.ics.uci.edu/ml/index.php'
driver.get(url)

In [4]:
datasetbtn=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a')
datasetbtn.click()

In [24]:
Dataset_name=[]
Data_type=[]
Task=[]
Attribute_type=[]
Instances=[]
Attribute=[]
Year=[]
Table=[]
try:
    tabletags=driver.find_elements_by_xpath('//table[@border="1"]/tbody/tr')
    for i in tabletags[1:]:
        Table.append(i.text.split("\n"))
except NoSuchElementException:
    print("Exception Raised ",e)

# Making DataFrame
pd.DataFrame(Table,columns=['Dataset name','Data Type','Task','Attribute Type','No. Of Instances','No. Of Attributes','Year'])

,Dataset name,Data Type,Task,Attribute Type,No. Of Instances,No. Of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,Recommender-Systems,Categorical,37711,294,1998,None
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twit...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,Classification,1014,7,2020,None,None
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mo...,Univariate,Regression,Real,4000,2,2021